rules = [
    "DOMAIN-SUFFIX,hlf01.site,DIRECT",
    "DOMAIN-SUFFIX,cnki.net,DIRECT",
    "DOMAIN-SUFFIX,mail.icloud.com.cn,🔰国外流量",
    "DOMAIN-SUFFIX,events.data.microsoft.com,🔰国外流量",
    "DOMAIN-SUFFIX,googlevideo.com,🎬Youtube",
    "DOMAIN-SUFFIX,ytimg.com,🎬Youtube",
    "DOMAIN-SUFFIX,ggpht.com,🎬Youtube",
    "DOMAIN-SUFFIX,telegram.me,✈️Telegram",
    "DOMAIN-SUFFIX,telegram.org,✈️Telegram",
    "DOMAIN-KEYWORD,openai,🌍OpenAI",
]
proxy_groups = [
    {"name": "🌍OpenAI", "type": "select"},
    {
        "name": "🇨🇳香港",
        "type": "url-test",
        "url": "http://www.gstatic.com/generate_204",
        "interval": 300,
        "lazy": True,
    },
    {
        "name": "🇯🇵日本",
        "type": "url-test",
        "url": "http://www.gstatic.com/generate_204",
        "interval": 300,
        "lazy": True,
    },
    {
        "name": "🇨🇳台湾",
        "type": "url-test",
        "url": "http://www.gstatic.com/generate_204",
        "interval": 300,
        "lazy": True,
    },
    {
        "name": "🇺🇸美国",
        "type": "url-test",
        "url": "http://www.gstatic.com/generate_204",
        "interval": 300,
        "lazy": True,
    },
    {
        "name": "🇸🇬新加坡",
        "type": "url-test",
        "url": "http://www.gstatic.com/generate_204",
        "interval": 300,
        "lazy": True,
    },
    {
        "name": "🇰🇷韩国",
        "type": "url-test",
        "url": "http://www.gstatic.com/generate_204",
        "interval": 300,
        "lazy": True,
    },
    {
        "name": "🇩🇪德国",
        "type": "url-test",
        "url": "http://www.gstatic.com/generate_204",
        "interval": 300,
        "lazy": True,
    },
    {
        "name": "🇬🇧英国",
        "type": "url-test",
        "url": "http://www.gstatic.com/generate_204",
        "interval": 300,
        "lazy": True,
    },
    {
        "name": "🇫🇷法国",
        "type": "url-test",
        "url": "http://www.gstatic.com/generate_204",
        "interval": 300,
        "lazy": True,
    },
    {
        "name": "🇺🇳非专线",
        "type": "url-test",
        "url": "http://www.gstatic.com/generate_204",
        "interval": 300,
        "lazy": True,
    },
    {
        "name": "🇨🇳专线",
        "type": "url-test",
        "url": "http://www.gstatic.com/generate_204",
        "interval": 300,
        "lazy": True,
    },
]
in_group_proxies = [
    {
        "name": "🔰国外流量",
        "groups": [
            "🇨🇳专线",
            "🇺🇳非专线",
            "🇨🇳香港",
            "🇯🇵日本",
            "🇺🇸美国",
            "🇸🇬新加坡",
            "🇰🇷韩国",
            "🇨🇳台湾",
            "🇩🇪德国",
            "🇬🇧英国",
            "🇫🇷法国",
        ],
    },
    {
        "name": "🎬国外媒体",
        "groups": [
            "🇨🇳专线",
            "🇺🇳非专线",
            "🇨🇳香港",
            "🇯🇵日本",
            "🇺🇸美国",
            "🇸🇬新加坡",
            "🇰🇷韩国",
            "🇨🇳台湾",
            "🇩🇪德国",
            "🇬🇧英国",
            "🇫🇷法国",
        ],
    },
    {"name": "✈️Telegram", "groups": ["🎬国外媒体", "🔰国外流量"]},
    {"name": "🎬Youtube", "groups": ["🎬国外媒体", "🔰国外流量"]},
    {"name": "🎬Netflix", "groups": ["🎬国外媒体", "🔰国外流量"]},
    {"name": "🎬哔哩哔哩", "groups": ["🚀直接连接"]},
    {
        "name": "🌍OpenAI",
        "groups": ["🇯🇵日本", "🇺🇸美国", "🇸🇬新加坡", "🇰🇷韩国", "🇩🇪德国", "🇬🇧英国", "🇫🇷法国"],
    },
    {
        "name": "🇺🇳非专线",
        "groups": [
            "🇨🇳香港",
            "🇯🇵日本",
            "🇺🇸美国",
            "🇸🇬新加坡",
            "🇰🇷韩国",
            "🇨🇳台湾",
            "🇩🇪德国",
            "🇬🇧英国",
            "🇫🇷法国",
        ],
    },
    {
        "name": "🇨🇳专线",
        "proxies": {"include": ["专线"]},
    },
    {
        "name": "🇨🇳香港",
        "proxies": {"include": ["香港"], "exclude": ["专线"]},
    },
    {
        "name": "🇯🇵日本",
        "proxies": {"include": ["日本"]},
    },
    {
        "name": "🇺🇸美国",
        "proxies": {"include": ["美国"]},
    },
    {
        "name": "🇸🇬新加坡",
        "proxies": {"include": ["新加坡"]},
    },
    {
        "name": "🇰🇷韩国",
        "proxies": {"include": ["韩国"]},
    },
    {
        "name": "🇨🇳台湾",
        "proxies": {"include": ["台湾"], "exclude": ["专线"]},
    },
    {
        "name": "🇩🇪德国",
        "proxies": {"include": ["德国"]},
    },
    {
        "name": "🇬🇧英国",
        "proxies": {"include": ["英国"]},
    },
    {
        "name": "🇫🇷法国",
        "proxies": {"include": ["法国"]},
    },
]
